[package]
name = "rsapksign"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
apk = "0.4.0"
clap = { version = "4.5.9", features = ["derive"] }
zip = { version = "2.1.3", default-features = false, features = ["constant_time_eq", "deflate"] }
